name: Deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 51.15.10.84
          username: davidmahe
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 42527
          script: |
            cd /home/davidmahe/prestashop/data/prestashop
            echo 'mmauhlea' | sudo -S chown -R davidmahe:davidmahe /home/davidmahe/prestashop/data/prestashop
            git fetch origin main
            git reset --hard origin/main
            echo 'mmauhlea' | sudo -S chown -R www-data:www-data /home/davidmahe/prestashop/data/prestashop
            echo 'mmauhlea' | sudo -S chown -R davidmahe:davidmahe /home/davidmahe/prestashop/data/prestashop/.git
            docker exec prestashop_app php bin/console cache:clear --env=prod --no-warmup
            echo "Deploiement OK - $(date)"
